### ISSUE TITLE
small caps?

### ISSUE THREAD

**Issue by ousia** [madig/cantarell-fonts#3]
@madig,

do you have any plans to add smcp to this font (at least for Latin chars)?

Many thanks for the work on this font.

**Comment by madig** [comment]
Hi! Not for now, as I haven't had any headspace for continuing work on Cantarell for years now. Maybe there will be a designer at some point who wants to add them :)

**Comment by ousia** [comment]
@madig, many thanks for your reply.

It is really a pity that such an awesome font lacks small caps.

Congratulations for the outstanding work to all who contributed to this typeface.

And huge thanks to @grautesk for the Greek glyphs (especially for the polytonic ones).
